### ISSUE TITLE
如果某个参数是以(xxx)结尾的，后导致之后的sql语句中的参数位置错位

### ISSUE THREAD

**Issue by wf2311** [kookob/RestoreSql#3]
如果某个参数是以(xxx)结尾的，后导致之后的sql语句中的参数位置错位

**Comment by kookob** [comment]
@wf2311 你用的是哪个版本，最新1.1.0的版本应该是修复的了，你可以更新试下。
springboot我本地暂时没搭建，后面我弄一个环境，一并支持下。
