### ISSUE TITLE
交流：Preparing与 Parameters之间存在空行或者分割行时不能restore

### ISSUE THREAD

**Issue by disperDuan** [kookob/RestoreSql#4]
Preparing与 Parameters 之间存在空行或者例如----的分割行时不能restore， RestoreSqlForSelection的line57 prevLine = null; 应该不用吧？

**Comment by kookob** [comment]
@disperDuan 
我是按默认的日志输出处理的，什么情况下会存在空行或---的分割？
这种特殊的，你可以加个判断处理掉。
往前多判断几行的内容。
